name: Enable auto merge

on:
  - pull_request

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: Omochice/.github/workflows/renovate-auto-merge.yml@main
        with:
          pr_number: ${{github.event.pull_request.number}}
